export const HOME = "/";
export const EMPLOYEE = "/employee";
export const EMAIL = "/email";
export const BONUSES = "/bonuses";
export const FIRSTBONUS = `${BONUSES}/firstBonus`
export const PROFILE = "/profile"
export const REGISTER ='/register';
export const LOGIN = '/'
export const ADMIN = "/Admin"
